spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
    data:
      learning: git
        Maitryee Das
        I am modifying my file
        this is a check 

        this is a change 

